export const coordinatorData = [
    {
        id: 1,
        operationCoordinator: "Tony Stark",
        team: "Avengers",
        action: "DELETED Task <#1A> for team Avengers",
        createdAtTime: "12:00:00",
        createdAtDate: "10/10/2015",
    },
    {
        id: 2,
        operationCoordinator: "Tony Stark",
        team: "Avengers",
        action: "UPDATED Task <#2A> for team Avengers",
        createdAtTime: "12:00:30",
        createdAtDate: "10/10/2015",
    },
    {
        id: 3,
        operationCoordinator: "Tony Stark",
        team: "Avengers",
        action: "CREATED Task <#5A> for team Avengers",
        createdAtTime: "12:40:00",
        createdAtDate: "10/11/2015",
    },
    {
        id: 4,
        operationCoordinator: "Tony Stark",
        team: "Avengers",
        action: "DELETED Task <#1A> for team Avengers",
        createdAtTime: "12:00:00",
        createdAtDate: "10/10/2015",
    },
    {
        id: 5,
        operationCoordinator: "Tony Stark",
        team: "Avengers",
        action: "DELETED Task <#1A> for team Avengers",
        createdAtTime: "12:00:00",
        createdAtDate: "10/10/2015",
    },
    {
        id: 6,
        operationCoordinator: "Tony Stark",
        team: "Avengers",
        action: "DELETED Task <#1A> for team Avengers",
        createdAtTime: "12:00:00",
        createdAtDate: "10/10/2015",
    },
    {
        id: 7,
        operationCoordinator: "Tony Stark",
        team: "Avengers",
        action: "DELETED Task <#1A> for team Avengers",
        createdAtTime: "12:00:00",
        createdAtDate: "10/10/2015",
    },
    {
        id: 8,
        operationCoordinator: "Tony Stark",
        team: "Avengers",
        action: "DELETED Task <#1A> for team Avengers",
        createdAtTime: "12:00:00",
        createdAtDate: "10/10/2015",
    },
    {
        id: 9,
        operationCoordinator: "Tony Stark",
        team: "Avengers",
        action: "DELETED Task <#1A> for team Avengers",
        createdAtTime: "12:00:00",
        createdAtDate: "10/10/2015",
    },
    {
        id: 10,
        operationCoordinator: "Tony Stark",
        team: "Avengers",
        action: "DELETED Task <#1A> for team Avengers",
        createdAtTime: "12:00:00",
        createdAtDate: "10/10/2015",
    },
    {
        id: 11,
        operationCoordinator: "Tony Stark",
        team: "Avengers",
        action: "DELETED Task <#1A> for team Avengers",
        createdAtTime: "12:00:00",
        createdAtDate: "10/10/2015",
    },
    {
        id: 12,
        operationCoordinator: "Tony Stark",
        team: "Avengers",
        action: "DELETED Task <#1A> for team Avengers",
        createdAtTime: "12:00:00",
        createdAtDate: "10/10/2015",
    },
]

export const driverData = [
    {
        id: 1,
        driver: "Alfred",
        team: "DC",
        task: "Current task is Task <#1A>",
        status: "COMPLETED",
        duration: "30 mins"
    },
    {
        id: 2,
        driver: "Happy",
        team: "Avengers",
        task: "Current task is Task <#1A>",
        status: "PENDING",
        duration: "25 mins"
    },
    {
        id: 3,
        driver: "Leo",
        team: "ShipBoyos",
        task: "Current task is Task <#1A>",
        status: "ONGOING",
        duration: "28 mins",
    },
    {
        id: 4,
        driver: "Soap",
        team: "COD",
        task: "Current task is Task <#1A>",
        status: "DELAYED",
        duration: "35 mins",
    },
    {
        id: 5,
        driver: "Han Solo",
        team: "JEDI",
        task: "Current task is Task <#1A>",
        status: "FAILED",
        duration: "28 mins",
    },
    {
        id: 6,
        driver: "Maul",
        team: "Sith",
        task: "Current task is Task <#1A>",
        status: "COMPLETED",
        duration: "15 mins",
    }
]